version: '3'
# 定义三个服务nginx,php,mysql
services:
    nginx:
        # 依赖php服务，意味着在启动nginx之前先启动php
        depends_on:
            - php
        # nginx镜像的路径
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/nginx
        # 容器的/home/docker/nginx目录挂载主机中的/home/docker/nginx目录，
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
        volumes:
            - /home/docker/nginx:/home/docker/nginx
        # nginx意外退出时自动重启
        restart: always

        # 映射80和443端口
        ports:
            - "80:80"
            - "443:443"

        # 容器名称
        container_name: nginx    
    php:
        depends_on:
            - mysql
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/php-fpm
        restart: always
        volumes:
            - /home/docker/nginx/www:/home/docker/nginx/www
            - /home/docker/php:/home/docker/php
        container_name: php   

    mysql:
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/mysql
        volumes:
            - /home/docker/mysql:/home/docker/mysql
        restart: always
        # 设置MYSQL_ROOT_PASSWORD环境变量，这里是设置mysql的root密码。这里为root。
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: mysql

apache:
    image: httpd:latest
    restart: always
    depends_on:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./src/:/usr/local/apache2/htdocs/:rw
        - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
        - ./apache/conf/extra/httpd-vhosts.conf:/usr/local/apache2/extra/httpd-vhosts.conf:ro
        - ./log/nginx/:/var/log/nginx/:rw
    links:
        - php
    container_name: apache
php:
    image: github.com/AprilOneDay/docker_php
    restart: always
    depends_on:
        - mysql
    expose:
        - "9000"
    volumes:
        - ./src/:/var/www/html/:rw
        - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./php/log/:/var/log/php-fpm/:rw
    links:
        - mysql:mysql
    container_name: php        

mysql:
    image: mysql:latest
    restart: always
    ports:
        - "3306:3306"
    volumes:
        - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./mysql/:/var/lib/mysql/:rw
        - ./log/mysql/:/var/log/mysql/:rw
    environment:
        MYSQL_ROOT_PASSWORD: "1q2w3e4r"
    container_name: mysql