# version: '2'
# services:
    mysql:
        # image: mysql:5.7
        build: ./mysql/
        restart: always
        privileged: true
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ./mysql/data/:/var/lib/mysql/:rw
            - ./mysql/log/:/var/log/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: "1qq2ww3ee4rr"
        container_name: mysql
    # mysql主重备份
    # mysqlsrv:
    #     # image: mysql:5.7
    #     build: ./mysqlsrv/
    #     restart: always
    #     privileged: true
    #     ports:
    #         - "3316:3306"
    #     volumes:
    #         - ./mysqlsrv/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    #         - ./mysqlsrv/data/:/var/lib/mysql/:rw
    #         - ./mysqlsrv/log/:/var/log/mysql/:rw
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "1qq2ww3ee4rr"
    #     container_name: mysqlsrv
    jenkins:
        build: ./jenkins/
        restart: always
        privileged: true
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./jenkins/src:/var/jenkins_home:rw
        container_name: jenkins
        links:
            - svn:svn
    svn:
        image: garethflowers/svn-server
        restart: always
        privileged: true
        ports:
            - "3690:3690"
        volumes:
            - ./svn/src:/var/opt/svn:rw
        container_name: svn
    php:
        #depends_on:
        #    - mysql
        build: ./php/
        container_name: php
        restart: always
        privileged: true
        links:
            - mysql:mysql
        volumes:
            - ./src/:/var/www/html/:rw
            - ./src/data:/var/www/html/data:rw
            - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./php/log/:/var/log/php-fpm/:rw
        expose:
            - "9000"        
    nginx:
        build: ./nginx/
        container_name: nginx
        restart: always
        privileged: true
        links:
            - php:php
        volumes:
            - ./src/:/var/www/html/:rw
            - ./src/data:/var/www/html/data:rw
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
            - ./nginx/conf/ssl/:/etc/nginx/ssl/
            - ./nginx/log/:/var/log/nginx/:rw
        ports:
            - "443:443"
            - "80:80"

    
            