version: '3'
# 定义三个服务nginx,php,mysql
services:
    nginx:
        # 依赖php服务，意味着在启动nginx之前先启动php
        depends_on:
            - php
        # nginx镜像的路径
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/nginx
        # 容器的/home/docker/nginx目录挂载主机中的/home/docker/nginx目录，
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
        volumes:
            - /home/docker/nginx:/home/docker/nginx
        # nginx意外退出时自动重启
        restart: always

        # 映射80和443端口
        ports:
            - "80:80"
            - "443:443"

        # 容器名称
        container_name: nginx    
    php:
        depends_on:
            - mysql
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/php-fpm
        restart: always
        volumes:
            - /home/docker/nginx/www:/home/docker/nginx/www
            - /home/docker/php:/home/docker/php
        container_name: php   

    mysql:
        image: registry.cn-hangzhou.aliyuncs.com/centos-bz/mysql
        volumes:
            - /home/docker/mysql:/home/docker/mysql
        restart: always
        # 设置MYSQL_ROOT_PASSWORD环境变量，这里是设置mysql的root密码。这里为root。
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: mysql

apache:
  image: httpd:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php:5.6
php5.6:
  build: php:5.6
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"